# Group by and Aggregating

In [53]:
import pandas as pd
df = pd.read_csv(r"C:\Nazim Khan\Data Analytics\Python using jupyter Notebook\Pandas_main\Flavors.csv")

In [54]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [58]:
df.groupby('Base Flavor').mean(numeric_only=True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [65]:
df.groupby('Base Flavor')[['Flavor','Liked']].count()

             Flavor  Liked
Base Flavor
Chocolate         3      3
Vanilla           6      6

In [66]:
df.groupby('Base Flavor')[['Flavor Rating','Texture Rating','Total Rating']].sum()

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [69]:
df.groupby('Base Flavor').agg({'Flavor Rating':['min','max','sum','count'],'Texture Rating':['min','max','sum','count'] })

            Flavor Rating                   Texture Rating
                      min   max   sum count            min  max   sum count
Base Flavor
Chocolate             8.2   8.8  25.2     3            7.0  7.6  21.7     3
Vanilla               2.3  10.0  34.2     6            3.4  8.0  33.9     6

In [74]:
df.groupby('Flavor').describe()

                       Flavor Rating                                          \
                               count  mean std   min   25%   50%   75%   max
Flavor
Cake Batter                      1.0   6.5 NaN   6.5   6.5   6.5   6.5   6.5
Chocolate                        1.0   8.8 NaN   8.8   8.8   8.8   8.8   8.8
Chocolte Fudge Brownie           1.0   8.2 NaN   8.2   8.2   8.2   8.2   8.2
Cookie Dough                     1.0   6.9 NaN   6.9   6.9   6.9   6.9   6.9
Mint Chocolate Chip              1.0  10.0 NaN  10.0  10.0  10.0  10.0  10.0
Neapolitan                       1.0   3.8 NaN   3.8   3.8   3.8   3.8   3.8
Pistachio                        1.0   2.3 NaN   2.3   2.3   2.3   2.3   2.3
Rocky Road                       1.0   8.2 NaN   8.2   8.2   8.2   8.2   8.2
Vanilla                          1.0   4.7 NaN   4.7   4.7   4.7   4.7   4.7

                       Texture Rating       ...           Total Rating        \
                                count mean  ...  75%  max        count  mean
Flavor                                      ...
Cake Batter                       1.0  6.0  ...  6.0  6.0          1.0  12.5
Chocolate                         1.0  7.6  ...  7.6  7.6          1.0  16.6
Chocolte Fudge Brownie            1.0  7.1  ...  7.1  7.1          1.0  15.3
Cookie Dough                      1.0  6.5  ...  6.5  6.5          1.0  13.4
Mint Chocolate Chip               1.0  8.0  ...  8.0  8.0          1.0  18.0
Neapolitan                        1.0  5.0  ...  5.0  5.0          1.0   8.8
Pistachio                         1.0  3.4  ...  3.4  3.4          1.0   5.7
Rocky Road                        1.0  7.0  ...  7.0  7.0          1.0  15.2
Vanilla                           1.0  5.0  ...  5.0  5.0          1.0   9.7


                       std   min   25%   50%   75%   max
Flavor
Cake Batter            NaN  12.5  12.5  12.5  12.5  12.5
Chocolate              NaN  16.6  16.6  16.6  16.6  16.6
Chocolte Fudge Brownie NaN  15.3  15.3  15.3  15.3  15.3
Cookie Dough           NaN  13.4  13.4  13.4  13.4  13.4
Mint Chocolate Chip    NaN  18.0  18.0  18.0  18.0  18.0
Neapolitan             NaN   8.8   8.8   8.8   8.8   8.8
Pistachio              NaN   5.7   5.7   5.7   5.7   5.7
Rocky Road             NaN  15.2  15.2  15.2  15.2  15.2
Vanilla                NaN   9.7   9.7   9.7   9.7   9.7

[9 rows x 24 columns]